### ISSUE TITLE
generic item file? 

### ISSUE THREAD

**Issue by tehmilcho** [Rosi2143/habpanel-widget-HMIP-eTRV-x#2]
Hey,
I would use your widget with HABpanel in iobroker but I don't get with the generic item file.

I understand what its for etc but where is the file? Must I create the file(path, name etc)?

Greetings Milcho

**Comment by Rosi2143** [comment]
Well, I don't know iobrocker - I only use openHAB.

There I just created the items in any item file - in homatic_ip.items to be precise. But manually - to have speaking, readable names I can understand when they pop up in traces. I don't like the item names that are automatically created.

I'll never tested it outside openHAB2. I didn't even know that you can use HABpanel also with iobroker. So I had a short look into some YT videos. And yes it seems like you have to create variables with the correct names as new items yourself also in iobroker.

Sorry for that.

**Comment by tehmilcho** [comment]
hey Rosi,

after i opend the issue i searched a littlebit in the Internet for this stuff and the file locations but i cant find any usefull informations. Its seems like HABpanel in Iobroker is somekind of a strange port from Openhab. I wars even not able to find where "Iobroker HABpanel" will save the "Custom Widgets" from the Gallery. 

I think to create "objects" with the names will not help because i tried allready to put in the original object-names without success. I also have openhab2 as well but only for Zwave-based-Devices and i just control it over Iobroker. 

Offtopic: In the moment i use another DIY Smarthome System - Pimatic as UI, Rules-System and to control some Devices directly but its alot of work to push everything from Iobroker to Pimatic etc.

In the Iobroker-Objects is a Object "habpanel configuration":

![image](https://user-images.githubusercontent.com/22918349/98736815-9fa68b00-23a5-11eb-84e1-a17a5df860b2.png)
[iobroker.conf.txt](https://github.com/Rosi2143/habpanel-widget-HMIP-eTRV-x/files/5520329/iobroker.conf.txt)

maybe i have to enter the list there?

In Iobroker the the Objects for HMIP looks like this:
![image](https://user-images.githubusercontent.com/22918349/98737100-07f56c80-23a6-11eb-8db0-eefa4d2e59f5.png)

**Comment by tehmilcho** [comment]
Okay .. it will work with little changes ... in my frist attempt... but HABpanel it selfs seems buggy as hell .. if i build everything that i looks nice on my phone it is huge on my PC Screen.. so crappy. 

[HmiP-eTRV-2.widget.txt](https://github.com/Rosi2143/habpanel-widget-HMIP-eTRV-x/files/5520852/HmiP-eTRV-2.widget.txt)

Anyway .. i know how its works .. maybe i rebuild it for Iobroker and send you the new Json for Iobroker if i will use Habpanel and do not stick to Pimatic as UI.
